### ISSUE TITLE
Running on arduino  uno

### ISSUE THREAD

**Issue by IuryAlves** [jensnockert/dueboot#2]
There is a way to run into arduino uno ?

**Comment by jhoogeboom** [comment]
maybe something like this?
https://github.com/avr-llvm/llvm

**Comment by IuryAlves** [comment]
@jhoogeboom  I will take a look

**Comment by jhoogeboom** [comment]
@IuryAlves It's still early days it seems, but if you get it running, I'd be interested in your findings. @jensnockert Have you already seen this backend for AVR, or dismissed it because still in development?

**Comment by auroranockert** [comment]
Last time I checked it couldn't actually build anything, but it can have changed. I only have an ARM Arduino though, so I couldn't really test anything very well.

**Comment by flosse** [comment]
[Arduino seems to be supported by avr-llvm](https://github.com/avr-llvm/llvm/issues/139) and there even is a [rust fork for avr](https://github.com/avr-rust/rust) so it might be possible now?!

**Comment by jhoogeboom** [comment]
looks positive, have you tried?

**Comment by auroranockert** [comment]
Would be cool, but I don't have the hardware so can't test :C

**Comment by jhoogeboom** [comment]
was more directed @flosse, but maybe I can send you a spare avr-arduino @jensnockert ?

**Comment by auroranockert** [comment]
That seems like a lot of work, maybe I can find one around the office, I'll ask around.

**Comment by flosse** [comment]
@shepmaster seems be be [very close to it](http://jakegoulding.com/blog/2016/01/02/rust-on-an-arduino-uno/)!

**Comment by shepmaster** [comment]
@flosse [Close, but so far away](http://jakegoulding.com/blog/2016/01/17/rust-on-an-arduino-uno-part-2/). I can light up an LED some of the time, but can't do addition yet! :heavy_plus_sign: :heavy_minus_sign: :heavy_multiplication_x: :heavy_division_sign: :confused: :smile_cat:
